# SyncLite logger sample config. Edit `device-type` and `db-path` to match
# the sample you're running. Default = transactional SQLite.

device-name=sampledevice
db-engine=SQLITE
device-type=SQLITE
db-path=sample_device_sqlite.db
local-data-stage-directory=synclite-stage
