device-name=sampledevice
db-engine=SQLITE
device-type=SQLITE
local-data-stage-directory=synclite-stage

dst-type=POSTGRES
dst-connection-string=postgresql://postgres:postgres@localhost:5432/syncdb
dst-database=syncdb
dst-schema=syncschema
dst-sync-mode=CONSOLIDATION
